add: filesystem write configurations
ArroyoSystems/arroyo pull request #392
Opened 2023-11-06 19:03 UTC by harshit2283

2023-11-06 20:13 UTC, jacksonrnewhouse requested changes
Only must-have is it working on the multipart writer.

2023-11-06 20:13 UTC, jacksonrnewhouse commented on arroyo-worker/src/connectors/filesystem/local.rs
> +        let filename_strategy = if self.filename_strategy == FilenameStrategy::Uuid {
What about calling this something like `filename_base`?

2023-11-09 21:41 UTC, harshit2283 commented on arroyo-worker/src/connectors/filesystem/local.rs
> +    filenaming: Filenaming,
Makes sense, have kept a single struct

2023-11-09 21:42 UTC, harshit2283 commented on arroyo-worker/src/connectors/filesystem/local.rs
>      fn get_or_insert_writer(&mut self, partition: &Option<String>) -> &mut V {
I've added redundant code for now, will refactor and unify.

2023-11-14 18:30 UTC, jacksonrnewhouse approved these changes

2023-11-14 18:30 UTC, merged