Add async UDFs
ArroyoSystems/arroyo pull request #483
Opened 2024-01-10 00:59 UTC by jbeisen

Add a new 'AsyncMapOperator' that applies an async udf to its input.

Async UDFs use the existing interface for defining the UDF and are called in SQL the same as non-async UDFs. Options are specified in a comment similar to dependencies.

2024-01-11 23:18 UTC, jacksonrnewhouse requested changes
a couple stylistic things I'd like to see addressed.

2024-01-11 23:18 UTC, jacksonrnewhouse commented on arroyo-datastream/src/lib.rs
> +                    let udf_wrapper = quote!({
I think there's too much logic here, and as a consequence too many fields on AsyncMapOperator. I think it'd be better to generate more of the code in arroyo-sql.

2024-01-11 23:18 UTC, jacksonrnewhouse commented on arroyo-sql/src/operators.rs
> +        unreachable!()
This seems like not the approach. The idea behind the `CodeGenerator<Context, OutputValue, OutputType: ToTokens>` trait is that you specify how to produce some syn type ToTokens, given a Context and an OutputValue. I think you want the code after `  RecordTransform::AsyncUdfProjection(a) => {` to be specified in the generate() method of a CodeGenerator implementation.

2024-01-11 23:18 UTC, jacksonrnewhouse commented on arroyo-worker/src/operators/async_map.rs
> +            let key = format!("{},{}", ctx.task_info.task_index, i);
The key should just be a tuple. (usize, usize) is a valid key here.

2024-01-11 23:54 UTC, mwylde commented
This query is panicking in the planner:

```sql
create table logs (
    ip TEXT,
    city TEXT GENERATED ALWAYS AS (get_city(ip))
) with (
    connector = 'sse',
    endpoint = 'http://127.0.0.1:9563/sse',
    format = 'json'
);

select city
from logs;
```

with 

```
2024-01-11T23:52:08.418511Z ERROR arroyo_server_common: panicked at arroyo-sql/src/expressions.rs:269:21:
async udf appeared in a non-projection context panic.file="arroyo-sql/src/expressions.rs" panic.line=269 panic.column=21
2024-01-11T23:52:08.418876Z  WARN arroyo_api::pipelines: failed to generate SQL program
```

2024-01-12 00:07 UTC, mwylde commented
Another panic if you try to group by an async udf:

```sql
select 
    get_city(logs.ip) as city, 
    count(*)
from logs
group by 1;
```

```
2024-01-12T00:06:33.748816Z ERROR arroyo_server_common: panicked at arroyo-sql/src/expressions.rs:269:21:
async udf appeared in a non-projection context panic.file="arroyo-sql/src/expressions.rs" panic.line=269 panic.column=21
2024-01-12T00:06:33.749935Z  WARN arroyo_api::pipelines: failed to generate SQL program
```

2024-01-12 00:43 UTC, mwylde commented on arroyo-macro/src/lib.rs
> +                                    timestamp: input.timestamp.clone(),
this clone is a no-op because SystemTime implements Copy

2024-01-12 00:43 UTC, mwylde commented
This is really great! I'm so excited to see how people use this.

2024-01-12 21:00 UTC, jbeisen commented on arroyo-datastream/src/lib.rs
> +        timeout_seconds: u64,
I don't think so because it gets deserialized from the toml in the UDF definition.

2024-01-15 23:16 UTC, mwylde commented on arroyo-rpc/src/lib.rs
> +    10
This seems very low to me. If an async udf takes just 50ms to run (pretty typical for a DB lookup) this limits us to 200 events/sec. I'd make this at least 100.

2024-01-16 01:23 UTC, jacksonrnewhouse approved these changes

2024-01-16 01:39 UTC, merged