setting imagePullSecrets for workers
ArroyoSystems/arroyo pull request #652
Opened 2024-06-10 13:23 UTC by chokosabe

Setting the imagepullsecrets. Not sure this is the best location to do this in.

2024-06-11 18:13 UTC, mwylde requested changes
This is a great start but need a little more work

2024-06-11 19:45 UTC, chokosabe commented
Added the changes requested. There does seem to be an intermittent build error with mqtt.

2024-06-11 20:26 UTC, chokosabe commented
Updates pushed up. Resolved all the changes.

2024-06-12 19:49 UTC, mwylde requested changes
This still isn't quite working. It might be useful to try testing it locally with docker desktop. With a local k8s environment, you can test it by creating a values.yaml file like this:

```
artifactUrl: "/tmp/arroyo-test"
checkpointUrl: "/tmp/arroyo-test"

volumes:
  - name: checkpoints
    hostPath:
      path: /tmp/arroyo-test
      type: DirectoryOrCreate

volumeMounts:
  - name: checkpoints
    mountPath: /tmp/arroyo-test
```

Then building an image from your branch and deploying it locally:

```
$ docker build . -f docker/Dockerfile -t ghcr.io/arroyosystems/arroyo:tip --target arroyo
$ helm install arroyo  k8s/arroyo -f values.yaml 
```

2024-06-12 19:49 UTC, mwylde commented on k8s/arroyo/templates/configmap.yaml
> +        command: ["/app/arroyo-bin --config-dir /config worker"]
This still isn't quite right. With this, trying to run this in helm gives the error 

```
Configuration is invalid!
  • invalid type: found sequence, expected a string for key "default.kubernetes-scheduler.worker.command" in /root/.config/arroyo/config.yaml YAML file
```
It should be restored to what it currently is in master.

2024-06-12 19:49 UTC, mwylde commented on k8s/arroyo/templates/configmap.yaml
> +        {{- with .Values.imagePullSecrets }}
`image_pull_secrets` is defined as a string, but here it's passed in an object which fails:
```
Configuration is invalid!
  • invalid type: found unit, expected a string for key "default.kubernetes-scheduler.worker.image-pull-secrets" in /root/.config/arroyo/config.yaml YAML file
```

2024-06-12 19:49 UTC, mwylde commented on crates/arroyo-rpc/default.toml
> +image-pull-secrets = "IfNotPresent"
Is this a sensible default for this?

2024-07-01 22:13 UTC, mwylde approved these changes
Thanks for the contribution! I've gone ahead and rebased on master and fixed a couple of issues so that we can get this into the next release.

2024-07-01 22:23 UTC, merged