Non-data fields - Metadata fields to Kafka Connector
ArroyoSystems/arroyo pull request #765
Opened 2024-10-24 05:51 UTC by vaibhawvipul

enabling users to query using the following syntax - 

```sql
create table users (
    id TEXT,
    name TEXT,
    offset BIGINT GENERATED ALWAYS AS (metadata('offset_id')) STORED
) with (
    connector = 'kafka',
    ...
);
```

Demo - 
<img width="1143" alt="Screenshot 2024-10-24 at 11 21 10 AM" src="https://github.com/user-attachments/assets/ee0caa1e-dde8-421c-9ee2-004e484787c8">

2024-10-28 05:00 UTC, mwylde commented on crates/arroyo-planner/src/tables.rs
> +                                                "Unsupported argument format.".to_string();
I'm a bit confusing by the intent here—this string is created by never used. Is this meant to return an error?

2024-10-28 05:01 UTC, mwylde commented on crates/arroyo-planner/src/tables.rs
> +                let generating_expression =
This function has very deep nesting and the logic is quite hard to follow. Is there a way to simplify it?

2024-10-28 05:02 UTC, mwylde commented on crates/arroyo-connectors/src/kafka/source/mod.rs
> +                                    metadata_fields: self.metadata_fields.clone(),
Can we avoid these clones?

2024-10-28 05:08 UTC, mwylde commented on crates/arroyo-formats/src/de.rs
> +    kafka_metadata_builder: Option<(Int64Builder, Int32Builder, StringBuilder)>,
This approach is very specific to Kafka, but the goal for this project is to have a generic metadata system that any connector can opt into with its specific metadata fields. How can we make the deserialization support work for whatever metadata fields a connector has?

2024-10-29 02:59 UTC, mwylde requested changes
Great progress on the PR!

A few remaining issues.

We're now validating metadata names (although the key/value are switched), but we're missing two types of validations for the user:

* Data types, which if the user sets the wrong type they get a runtime error, for example if they declare

```
    offset_id INT GENERATED ALWAYS AS (metadata('offset_id')) STORED
```

and we're not validating that the metadata columns have only a metadata function in them, so this plans:

```
    offset_id BIGINT GENERATED ALWAYS AS (concat(metadata('offset_id'), '1')) STORED
```

Beyond that, I'd like to see some tests, both for the deserialization logic and for planning. It might also be worth modifying the kafka tests to use metadata fields.

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-connectors/src/kafka/mod.rs
> +                if !allowed_metadata_udf_args.contains(&key.as_str()) {
This should be checking the value rather than the key (since the key is the field name, not the metadata name)

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-connectors/src/kafka/source/mod.rs
> +                                let connector_metadata = if self.metadata_fields.is_some() {
This can be made a bit cleaner with an if let statement

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-formats/src/de.rs
> +                        if self.additional_fields_builder.is_some() {
Same here, this can be an if let

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-formats/src/de.rs
> +                if additional_fields.is_some() {
This can also be an if let

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-formats/src/de.rs
> +                if let Some(additional_fields) = additional_fields {
This code is duplicated a couple of times, is it possible to abstract it out?

2024-10-29 02:59 UTC, mwylde commented on crates/arroyo-formats/src/de.rs
> +                                columns.remove(idx);
I find this logic a bit hard to follow—why are we removing columns?

2024-10-30 09:01 UTC, vaibhawvipul commented
@mwylde can you please trigger the CI again? I am asking because my last commit ran successfully, the failed CI is on master merge.

2024-10-30 15:53 UTC, mwylde approved these changes
Thanks, this is a great contribution!

2024-10-30 16:06 UTC, merged